import Head from 'next/head';
import Name from '../Components/Name';
import Nav from '../Components/Nav';
import Blob from '../Components/Blob';
import Intro from '../Components/Intro';
import TechStack from '../Components/TechStack';
import Projects from '../Components/Projects';

import { useState, useRef, useEffect } from 'react';

import { Parallax, ParallaxLayer } from '@react-spring/parallax';

export default function Home() {

  return (
    <>
      <Head>
        <title>Atomic Code</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="rgb(0, 182, 243)" ></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ overflow: 'clip' }}>

        <Nav />
        <Blob />


        <Parallax pages={5} >

          <ParallaxLayer>
            <Name />
          </ParallaxLayer>


          <ParallaxLayer offset={1} speed={.2}>
            <Intro />
          </ParallaxLayer>

          <ParallaxLayer offset={2} factor={1} speed={1}>
            <Projects />
          </ParallaxLayer>

          <ParallaxLayer offset={3} factor={1} speed={1}>
            <TechStack />
          </ParallaxLayer>


        </Parallax>



      </main>
    </>
  );
}
