import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';

import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {

  const [name, setName] = useState('ATOMIC CODE');

  const letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ ';
  const ATOMICCODE = 'ATOMIC CODE';

  const changeName = () => {

    let iterations = 1 / 3;

    const interval = setInterval(() => {
      const word = name.split('')
        .map((letter, index) => {
          if (index < iterations) {
            return ATOMICCODE[index];
          }

          return letters[Math.floor(Math.random() * 26)];
        })
        .join('');
      setName(word);

      if (iterations >= ATOMICCODE.length) clearInterval(interval);

      iterations += 1;
    }, 30);

  };

  // document.querySelector('h1').onmouseover = event => {
  //   event.target.innerText = event.target.innerText.split('')
  //     .map(letter => letters[Math.floor(Math.random() * 26)])
  //     .join('');
  // };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black">

        <div className='flex h-screen items-center justify-center'>
          <h1 onMouseOver={changeName} className='text-white text-4xl'>{name}</h1>
        </div>

      </main>
    </>
  );
}
