import Head from 'next/head';
import Name from '../Components/Name';
import Nav from '../Components/Nav';
import Blob from '../Components/Blob';
import Intro from '../Components/Intro';
import TechStack from '../Components/TechStack';
import Projects from '../Components/Projects';
import Youtube from '../Components/Youtube';

import { useState, useRef, useEffect } from 'react';

import { Parallax, ParallaxLayer } from '@react-spring/parallax';

export default function Home() {

  return (
    <>
      <Head>
        <title>Atomic Code</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="rgb(0, 182, 243)" ></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ overflow: 'clip' }}>

        <Blob />

        <Parallax pages={5} >

          <ParallaxLayer>
            <Name />
          </ParallaxLayer>

          <ParallaxLayer offset={1} speed={.5
          }>
            <Intro />
          </ParallaxLayer>

          <ParallaxLayer offset={2} factor={1} speed={1}>
            <Projects />
          </ParallaxLayer>

          <ParallaxLayer offset={3} factor={1} speed={.5}>
            <TechStack />
          </ParallaxLayer>

          <ParallaxLayer offset={4} factor={2} speed={.2}>
            <Youtube />
          </ParallaxLayer>

          <div className="absolute z-10 bg-opacity-0 bg-black bottom-0 h-36 text-2xl text-white w-[100%]">
            <ul className='flex justify-center py-2 px-4'>
              <li className='mx-4 cursor-pointer'>aqbaghi@atomiccode.uk</li>
              <li className='mx-4 cursor-pointer'>+218 92 484 3238</li>
            </ul>
          </div>
        </Parallax>



      </main>

    </>
  );
}
